# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNHTMLtoPDF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RNHTMLtoPDF', :path => '../node_modules/react-native-html-to-pdf'
  # Pods for RNHTMLtoPDF

  target 'RNHTMLtoPDFTests' do
    # Pods for testing
  end

end
